version: '2.4'
services:
  api-manager:
    build: ./dockerfiles
    healthcheck:
      test: ["CMD", "nc", "-z","localhost", "9444"]
      interval: 10s
      start_period: 180s
      retries: 20
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PROFILE_NAME=control-plane
    volumes:
      - ./conf:/home/wso2carbon/wso2-config-volume
    ports:
      - "9444:9444"
      - "9764:9764"
      - "8281:8281"
      - "8244:8244"
      - "5673:5673"
      - "9612:9612"
      - "9712:9712"
